Finish to work on analytics page
lzhabo/puzzle-lend pull request #39
Opened 2022-11-01 17:21 UTC by SEPEZHO

2022-11-01 18:28 UTC, lzhabo requested changes

2022-11-01 18:28 UTC, lzhabo commented on src/screens/AnalyticsScreen/AnalyticsTotalData.tsx
> +                  {(s.amountTotal / vm.priceForToken(s).toNumber()).toFixed(2) +
toNumber делать не надо, если ты потом toFixed делаешь

2022-11-01 18:28 UTC, lzhabo commented on src/screens/AnalyticsScreen/AnalyticsScreenTable.tsx
> +//TODO пометка для себя я бы эти стили переписал без трех > div селекторов, а на классах
да, давай

2022-11-01 18:28 UTC, lzhabo commented on src/screens/AnalyticsScreen/AnalyticsScreenBaseInfo.tsx
> +      value: vm.popularOf("supply")[0]?.asset.name ?? "Loading..."
шо то слишком мудрено, надо проще сделать

2022-11-02 14:31 UTC, SEPEZHO commented on src/screens/AnalyticsScreen/AnalyticsTotalData.tsx
> +                  {(s.amountTotal / vm.priceForToken(s).toNumber()).toFixed(2) +
Там же возвращается BN который учавствует в мат операции (деление) и ток потом делается туфиксед от результата

2022-11-02 14:34 UTC, SEPEZHO commented on src/screens/AnalyticsScreen/AnalyticsScreenBaseInfo.tsx
> +      value: vm.popularOf("supply")[0]?.asset.name ?? "Loading..."
popularOf - функция которая возвращает массив с наиболее используемыми монетами. Она же используется для TotalValue виджета (там надо отобразить скок всего в пуле каких токенов). По сути я просто взял [0] элемент из этого массива и вытащил название токена. Переиспользовал ту же функцию что и для TotalValue.

2022-11-02 14:35 UTC, SEPEZHO commented on src/screens/AnalyticsScreen/AnalyticsTotalData.tsx
> +                  {(s.amountTotal / vm.priceForToken(s).toNumber()).toFixed(2) +
Так что без тунамбер деление не заробит. И тут уже вопрос делать конверт amountTotal в BN или прост BN в нумбер. Думаю так проще

2022-11-02 14:45 UTC, lzhabo commented on src/screens/AnalyticsScreen/AnalyticsTotalData.tsx
> +                  {(s.amountTotal / vm.priceForToken(s).toNumber()).toFixed(2) +
а, я в скобках запуталась 
думала ты делаешь числу тунамбер, что не учавствует в калькуляции

тогда надо лучше сделать так new BN(s.amountTotal).div(vm.priceForToken(s).toFixed(2)
 что бы не было дерацкого неправльного округления чисел, что свойственно в js

2022-11-02 15:02 UTC, SEPEZHO commented on src/screens/AnalyticsScreen/AnalyticsScreenBaseInfo.tsx
> +      value: vm.popularOf("supply")[0]?.asset.name ?? "Loading..."
А, ты про это. Окей, да. Я как раз хотел на скелетон сменить

2022-11-02 16:22 UTC, merged