Modals logic
lzhabo/puzzle-lend pull request #7
Opened 2022-10-15 10:41 UTC by matt5346

2022-10-15 11:45 UTC, lzhabo requested changes

2022-10-15 11:45 UTC, lzhabo commented on src/screens/Dashboard/DashboardModals/BorrowAssets.tsx
> +    let bcu = poolStats.reduce((acc: BN, stat: TPoolStats) => {
вот это все должно быть во вью моделе, а в компоненте прост отображение

2022-10-15 11:45 UTC, lzhabo commented on src/screens/Dashboard/DashboardModals/BorrowAssets.tsx
> +      isError = true;
все во вью модель

2022-10-15 11:45 UTC, lzhabo commented on src/screens/Dashboard/DashboardModals/BorrowAssets.tsx
> +                ? (+formatVal(amount, token?.decimals).times(
тоже во вью модель

2022-10-15 11:45 UTC, lzhabo commented on src/screens/Dashboard/DashboardModals/BorrowAssets.tsx
> +                  minWidth: "16px",
можешь просто вынести сверху и написать вот так 

const StyledBack= styled(Back)`
min-width: 16px
 и тд
`

2022-10-15 11:45 UTC, lzhabo commented on src/screens/Dashboard/DashboardModals/BorrowAssets.tsx
> +        <Checkbox
удаляй комменты

2022-10-15 11:45 UTC, lzhabo commented on src/screens/Dashboard/DashboardModals/DashboardModalBody.tsx
> +      {step === 0 && operationName === OPERATIONS_TYPE.SUPPLY && (
зачем тебе переменная степ не очень поняла? если у тебя табы меняются в зависимости от OPERATION_TYPE

2022-10-15 11:45 UTC, lzhabo commented on src/screens/Dashboard/DashboardModals/DashboardModalVM.tsx
> +        console.log(e, "---e");
логи удаляй

2022-10-15 11:45 UTC, lzhabo commented on src/screens/Dashboard/DashboardModals/RepayAssets.tsx
> +  const submitForm = () => {
тоже всю логику подсчета во вью модель

2022-10-15 11:47 UTC, matt5346 commented on src/screens/Dashboard/DashboardModals/DashboardModalBody.tsx
> +      {step === 0 && operationName === OPERATIONS_TYPE.SUPPLY && (
кстати да, что то сразу не обратил внимание

2022-10-18 17:20 UTC, lzhabo approved these changes

2022-10-18 17:23 UTC, merged